format = """
$username\
$hostname\
$python\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$character"""

add_newline = false

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
