format = """
$username\
$hostname\
$directory\
$python\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$character"""

add_newline = false

[directory]
style = "blue"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = '[$symbol($virtualenv )\[$version\]]($style) '
style = "bright-yellow"
