[window]
  opacity = 0.8
[font]
  size = 12
[font.normal]
  family = "ComicShannsMonoNerdFontMono"
  #family = "BigBlueTerm437NerdFontMono"
  #family = "HeavyDataNerdFont"
  #family = "ProggyCleanNerdFontMono"
  #family = "TerminessNerdFontMono"
  #family = "MonofurNerdFontMono"
  #family = "HasklugNerdFontMono"
